name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Production Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz"
          cache: true

      - name: Export HTML5 Game
        run: |
          mkdir -p build/web
          ~/.local/share/godot/godot --headless --export-release "Web" build/web/index.html

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Production
        run: netlify deploy --dir=build/web --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
