name: Deploy Godot Game to Netlify

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Export Godot Game
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # ✅ Manually install Godot 4.4
      - name: Download and Install Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_linux.x86_64.zip -O godot.zip
          unzip godot.zip
          chmod +x Godot_v4.4-stable_linux.x86_64
          mv Godot_v4.4-stable_linux.x86_64 godot
          mkdir -p ~/.local/bin
          mv godot ~/.local/bin/godot
          echo "$HOME/.local/bin" >> $GITHUB_PATH  # Add to PATH

          wget https://github.com/godotengine/godot/releases/download/4.4-stable/Godot_v4.4-stable_export_templates.tpz -O export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/4.4.stable/
          unzip export_templates.tpz -d ~/.local/share/godot/export_templates/4.4.stable/

      # ✅ Verify installation
      - name: Verify Godot Installation
        run: godot --version

      - name: Verify Export Templates
        run: ls -lah ~/.local/share/godot/export_templates/4.4.stable/

      # ✅ Open the project to ensure assets are imported
      - name: Preload Assets (Ensure All Resources Are Imported)
        run: godot --headless --editor --quit

      # ✅ Export game as HTML5
      - name: Export HTML5 Game
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      # ✅ Upload exported game as
