name: PR Checks (Lint & Test)

on:
  pull_request:

jobs:
  lint:
    name: Lint Godot Scripts
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GDLint
        run: |
          pip install gdtoolkit  # Installs GDLint

      - name: Run GDLint
        run: |
          gdformat --check .
          gdlint .

  test:
    name: Run Godot Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: firebelley/godot-export@v6
        with:
          godot-version: "4.4"

      - name: Run Godot Unit Tests
        run: |
          godot --headless --test

  build:
    name: Build & Export for Validation
    runs-on: ubuntu-latest
    needs: [lint, test]  # Only run if linting and tests pass

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Godot
        uses: firebelley/godot-export@v5
        with:
          godot-version: "4.4"

      - name: Export HTML5 Game
        run: |
          mkdir -p build/web
          godot --headless --export-release "Web" build/web/index.html

      - name: Upload exported game as artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-html5
          path: build/web

  preview:
    name: Deploy Preview to Netlify
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download built files
        uses: actions/download-artifact@v4
        with:
          name: godot-html5
          path: build/web

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy Preview (for PRs)
        run: |
          PREVIEW_URL=$(netlify deploy --dir=build/web --message "Preview for ${{ github.head_ref }}" --json | jq -r '.deploy_url')
          echo "Preview available at: $PREVIEW_URL"
          echo "Preview available at: $PREVIEW_URL" >> $GITHUB_STEP_SUMMARY
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
